/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package talèp;

import javax.swing.*;
import java.awt.Color;
/**
 *
 * @author grottelli.gabriele
 */
public class InerfacciaGrafica extends javax.swing.JFrame {
    private GestoreGioco gestore;
    private JButton[] listaBottoni;
    private JButton btnStart; // Il nuovo tasto Start

    public InerfacciaGrafica() {
        initComponents();
        gestore = new GestoreGioco(8);
        listaBottoni = new JButton[]{jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8};
        
        // Configurazione iniziale bottoni
        for(JButton b : listaBottoni) b.setEnabled(false);
        
        // Mostra subito le istruzioni
        mostraIstruzioni();
    }

    private void mostraIstruzioni() {
        JOptionPane.showMessageDialog(this, 
            "REGOLE DEL GIOCO:\n" +
            "1. Premi START per iniziare.\n" +
            "2. Colpisci la TALPA (+10 punti).\n" +
            "3. Click a vuoto: -5 punti e -2 secondi!\n" +
            "4. Hai 30 secondi di tempo.", 
            "Istruzioni", JOptionPane.INFORMATION_MESSAGE);
    }

    // Questo metodo va collegato al tasto Start (jButton9 o uno nuovo)
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {
        gestore.resettaGioco();
        btnStart.setEnabled(false); // Disabilita start durante il gioco
        
        for(JButton b : listaBottoni) b.setEnabled(true);
        
        gestore.avviaTimer(this::aggiornaLabels, () -> {
            aggiornaLabels();
            for(JButton b : listaBottoni) b.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Fine! Punteggio finale: " + gestore.getPunteggio());
            btnStart.setEnabled(true);
            btnStart.setText("Riprova");
        });

        gestore.avviaMovimentoTalpe(this::aggiornaBottoni);
    }

    private void aggiornaLabels() {
        Punteggio.setText("Punti: " + gestore.getPunteggio());
        Tempo.setText("Tempo: " + gestore.getTempoResiduo() + "s");
        if (gestore.getTempoResiduo() <= 5) Tempo.setForeground(Color.RED);
        else Tempo.setForeground(Color.BLACK);
    }

    private void aggiornaBottoni() {
        for (int i = 0; i < 8; i++) {
            if (gestore.getBuche().get(i).isOccupata()) {
                listaBottoni[i].setText("TALPA!");
                listaBottoni[i].setBackground(Color.RED);
            } else {
                listaBottoni[i].setText("Buca");
                listaBottoni[i].setBackground(null);
            }
        }
    }

    // Esempio di gestione click su una buca (ripetere per tutti i jButton)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if(gestore.isInCorso()) {
            gestore.colpisceBuca(0);
            aggiornaLabels();
            aggiornaBottoni();
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InerfacciaGrafica.class.getName());

    /**
     * Creates new form InerfacciaGrafica
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Tempo = new javax.swing.JTextField();
        Punteggio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Instruzioni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        Tempo.setText("jTextField1");
        Tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempoActionPerformed(evt);
            }
        });

        Punteggio.setText("jTextField2");
        Punteggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PunteggioActionPerformed(evt);
            }
        });

        jLabel1.setText("Punteggio");

        jLabel2.setText("Tempo");

        Instruzioni.setText("jButton9");
        Instruzioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstruzioniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton6)
                .addGap(210, 210, 210)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(Punteggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Instruzioni))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton1)
                        .addGap(223, 223, 223)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Punteggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(119, 119, 119)
                .addComponent(Instruzioni)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gestore.colpisceBuca(0); // Indice 0 per il bottone 1
        aggiornaLabels();
        aggiornaBottoni();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gestore.colpisceBuca(1); // Indice 0 per il bottone 1
        aggiornaLabels();
        aggiornaBottoni();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        gestore.colpisceBuca(2); // Indice 0 per il bottone 1
        aggiornaLabels();
        aggiornaBottoni();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        gestore.colpisceBuca(3); // Indice 0 per il bottone 1
        aggiornaLabels();
        aggiornaBottoni();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        gestore.colpisceBuca(4); // Indice 0 per il bottone 1
        aggiornaLabels();
        aggiornaBottoni();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        gestore.colpisceBuca(5); // Indice 0 per il bottone 1
        aggiornaLabels();
        aggiornaBottoni();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        gestore.colpisceBuca(6); // Indice 0 per il bottone 1
        aggiornaLabels();
        aggiornaBottoni();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        gestore.colpisceBuca(7); // Indice 0 per il bottone 1
        aggiornaLabels();
        aggiornaBottoni();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void TempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TempoActionPerformed

    private void PunteggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PunteggioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PunteggioActionPerformed

    private void InstruzioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstruzioniActionPerformed
        JOptionPane.showMessageDialog(this, 
        "Benvenuto! \nPrendi la talpa (+10pt). \nSe sbagli perdi 5pt e 2 secondi.", 
        "Istruzioni di Gioco", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_InstruzioniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InerfacciaGrafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Instruzioni;
    private javax.swing.JTextField Punteggio;
    private javax.swing.JTextField Tempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
