/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giocotalpa;

import javax.swing.*;
import java.awt.*;
import java.util.Random;
/**
 *
 * @author grott
 */
public class InterfacciaGrafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName());
    private JButton[] buche = new JButton[8];
    private boolean[] talpaPresente = new boolean[8];
    private int punteggio = 0;
    private boolean giocoAttivo = true;
    private Random random = new Random();
    /**
     * Creates new form InterfacciaGrafica
     */
    public InterfacciaGrafica() {
        initComponents();
        setSize(600, 400);  
        creaBuche();
        avviaThreadTalpe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creaBuche() {
        setLayout(new GridLayout(2, 4));

        for (int i = 0; i < 8; i++) {
            int index = i;

            buche[i] = new JButton("VUOTA");
            talpaPresente[i] = false;

            buche[i].addActionListener(e -> colpisciBuca(index));

            add(buche[i]);
        }
    }

    private synchronized void colpisciBuca(int index) {

        if (talpaPresente[index]) {
            punteggio += 10;
            buche[index].setText("COLPITA!");
            talpaPresente[index] = false;
        } else {
            punteggio -= 5;
        }

        setTitle("Punteggio: " + punteggio);
    }

    private void avviaThreadTalpe() {

        Thread generatore = new Thread(() -> {

            while (giocoAttivo) {

                int index = random.nextInt(8);

                if (!talpaPresente[index]) {

                    talpaPresente[index] = true;

                    SwingUtilities.invokeLater(() ->
                            buche[index].setText("TALPA!")
                    );

                    new Thread(() -> {
                        try {
                            Thread.sleep(2000); // tempo visibile
                        } catch (InterruptedException e) {
                        }

                        synchronized (InterfacciaGrafica.this) {
                            talpaPresente[index] = false;
                            SwingUtilities.invokeLater(() ->
                                    buche[index].setText("VUOTA")
                            );
                        }
                    }).start();
                }

                try {
                    Thread.sleep(1000); // tempo tra una talpa e l'altra
                } catch (InterruptedException e) {
                }
            }
        });

        generatore.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfacciaGrafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
