/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giocotalpa;

/**
 *
 * @author grottelli.gabriele
 */
public class InterfacciaGrafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName());

    /**
     * Creates new form InterfacciaGrafica
     */
    public InterfacciaGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Buca_1 = new javax.swing.JButton();
        Buca_2 = new javax.swing.JButton();
        Buca_3 = new javax.swing.JButton();
        Buca_4 = new javax.swing.JButton();
        Buca_5 = new javax.swing.JButton();
        Buca_6 = new javax.swing.JButton();
        Buca_7 = new javax.swing.JButton();
        Buca_8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Vineta BT", 2, 24)); // NOI18N
        jLabel1.setText("ACCHIAPPA LA TALPA");

        Buca_1.setText("jButton1");
        Buca_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buca_1ActionPerformed(evt);
            }
        });

        Buca_2.setText("jButton1");
        Buca_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buca_2ActionPerformed(evt);
            }
        });

        Buca_3.setText("jButton1");
        Buca_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buca_3ActionPerformed(evt);
            }
        });

        Buca_4.setText("jButton1");
        Buca_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buca_4ActionPerformed(evt);
            }
        });

        Buca_5.setText("jButton1");
        Buca_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buca_5ActionPerformed(evt);
            }
        });

        Buca_6.setText("jButton1");
        Buca_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buca_6ActionPerformed(evt);
            }
        });

        Buca_7.setText("jButton1");
        Buca_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buca_7ActionPerformed(evt);
            }
        });

        Buca_8.setText("jButton1");
        Buca_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buca_8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(Buca_4)
                        .addGap(136, 136, 136)
                        .addComponent(Buca_5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buca_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Buca_7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buca_1)
                                .addGap(108, 108, 108)
                                .addComponent(Buca_2)))
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Buca_3)
                            .addComponent(Buca_8))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buca_1)
                    .addComponent(Buca_2)
                    .addComponent(Buca_3))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buca_4)
                    .addComponent(Buca_5))
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buca_6)
                    .addComponent(Buca_7)
                    .addComponent(Buca_8))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Buca_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buca_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buca_1ActionPerformed

    private void Buca_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buca_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buca_2ActionPerformed

    private void Buca_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buca_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buca_3ActionPerformed

    private void Buca_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buca_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buca_4ActionPerformed

    private void Buca_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buca_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buca_5ActionPerformed

    private void Buca_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buca_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buca_6ActionPerformed

    private void Buca_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buca_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buca_7ActionPerformed

    private void Buca_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buca_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buca_8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfacciaGrafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buca_1;
    private javax.swing.JButton Buca_2;
    private javax.swing.JButton Buca_3;
    private javax.swing.JButton Buca_4;
    private javax.swing.JButton Buca_5;
    private javax.swing.JButton Buca_6;
    private javax.swing.JButton Buca_7;
    private javax.swing.JButton Buca_8;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
